databases:
  - name: docuseal-db
    plan: starter
    databaseName: docuseal
    user: docuseal

services:
  - type: redis
    name: docuseal-redis
    plan: starter
    maxmemoryPolicy: noeviction

  - type: web
    name: docuseal
    runtime: docker
    plan: starter
    healthCheckPath: /up
    disk:
      name: docuseal-storage
      mountPath: /data
      sizeGB: 10
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: docuseal-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: docuseal-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: WORKDIR
        value: /data
      - key: HOST
        sync: false

  - type: worker
    name: docuseal-worker
    runtime: docker
    dockerCommand: bundle exec sidekiq -C config/sidekiq.yml
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: docuseal-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: docuseal-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_ENV
        value: production
