databases:
  - name: docuseal-db
    plan: starter
    databaseName: docuseal
    user: docuseal

services:
  - type: web
    name: docuseal
    runtime: docker
    plan: starter
    healthCheckPath: /up
    ipAllowList: []
    disk:
      name: docuseal-storage
      mountPath: /data
      sizeGB: 10
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: docuseal-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: WORKDIR
        value: /data
      - key: HOST
        sync: false
